### ISSUE TITLE
[BUG] cri为containerd时,构建的镜像无法使用

### ISSUE THREAD

**Issue by fangzhengjin** [sealerio/basefs#53]
#### What happened:

感觉没有测试过cri为containerd的场景, 在`download.sh`中我看到无论是那种cri下载的文件都是`docker.tar.gz`
https://github.com/sealerio/basefs/blob/e02ef965622f99c6ac0ea0e4cbd454add1a893c3/context/download.sh#L111-L113

在`containerd.sh`中`containerd.tgz`文件明显不存在
https://github.com/sealerio/basefs/blob/e02ef965622f99c6ac0ea0e4cbd454add1a893c3/context/containerd/rootfs/scripts/containerd.sh#L32

其他的问题暂时没有细看, 想问下镜像仓库里发布的镜像真的是基于此脚本打包的吗?

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by riddlegit** [comment]
agree, containerd.sh and uninstall-containerd.sh not works, I can see some rows may be wrong:
`lsb_dist=$(utils_get_distribution)`
this function not in containerd.sh, maybe you should copy a same function from docker.sh and change the function name like this:
`utils_get_distribution() {
  lsb_dist=""
  # Every system that we officially support has /etc/os-release
  if [ -r /etc/os-release ]; then
    lsb_dist="$(. /etc/os-release && echo "$ID")"
  fi
  # Returning an empty string here should be alright since the
  # case statements don't act unless you provide an actual value
  echo "$lsb_dist"
}`
 
` tar -zxvf "${scripts_path}"/../tgz/containerd.tgz -C / `
should be change due to the folders copied to nodes' var/lib/sealer/data/xxx-cluster/rootfs/
` tar -zxvf "${scripts_path}"/../cri/docker.tgz -C / `

and some other files error, just can not go on
